Hooky.resources.register(:directory)  { Hooky::Resource::Directory }
Hooky.resources.register(:execute)    { Hooky::Resource::Execute }
Hooky.resources.register(:file)       { Hooky::Resource::File }
Hooky.resources.register(:hook_file)  { Hooky::Resource::HookFile }
Hooky.resources.register(:hooky_file) { Hooky::Resource::HookFile }
Hooky.resources.register(:link)       { Hooky::Resource::Link }
Hooky.resources.register(:mount)      { Hooky::Resource::Mount }
Hooky.resources.register(:rsync)      { Hooky::Resource::Rsync }
Hooky.resources.register(:scp)        { Hooky::Resource::Scp }
Hooky.resources.register(:service)    { Hooky::Resource::Service }
Hooky.resources.register(:template)   { Hooky::Resource::Template }
Hooky.resources.register(:zfs)        { Hooky::Resource::Zfs }
Hooky.resources.register(:logrotate)  { Hooky::Resource::Logrotate }
