Hookit.resources.register(:directory)      { Hookit::Resource::Directory }
Hookit.resources.register(:ensure_socket)  { Hookit::Resource::Socket }
Hookit.resources.register(:execute)        { Hookit::Resource::Execute }
Hookit.resources.register(:file)           { Hookit::Resource::File }
Hookit.resources.register(:hook_file)      { Hookit::Resource::HookFile }
Hookit.resources.register(:hookit_file)    { Hookit::Resource::HookFile }
Hookit.resources.register(:link)           { Hookit::Resource::Link }
Hookit.resources.register(:logrotate)      { Hookit::Resource::Logrotate }
Hookit.resources.register(:mount)          { Hookit::Resource::Mount }
Hookit.resources.register(:package)        { Hookit::Resource::Package }
Hookit.resources.register(:rsync)          { Hookit::Resource::Rsync }
Hookit.resources.register(:scp)            { Hookit::Resource::Scp }
Hookit.resources.register(:service)        { Hookit::Resource::Service }
Hookit.resources.register(:template)       { Hookit::Resource::Template }
Hookit.resources.register(:zfs)            { Hookit::Resource::Zfs }
